// File generated by Antigravity IDE for Sendzyy Firebase project
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for Sendzyy platform
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-PkzV-8Ruj4ExeiTYkDTo4hYEVaCBi48',
    appId: '1:316353739480:web:fed74e4dfc3c49f002b5ad',
    messagingSenderId: '316353739480',
    projectId: 'sendzyy',
    authDomain: 'sendzyy.firebaseapp.com',
    storageBucket: 'sendzyy.firebasestorage.app',
    measurementId: 'G-LNK86SE44R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfZyTQmjRLWjCDv4TaLratNlZFA_c7J9g',
    appId: '1:316353739480:android:0d3e637193fdba1902b5ad',
    messagingSenderId: '316353739480',
    projectId: 'sendzyy',
    storageBucket: 'sendzyy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACRCiYWdiCswCYB-9CdRIy5U_45rbgxW4',
    appId: '1:316353739480:ios:5edd1b7e307ba47a02b5ad',
    messagingSenderId: '316353739480',
    projectId: 'sendzyy',
    storageBucket: 'sendzyy.firebasestorage.app',
    iosBundleId: 'com.iflorainfopvtltd.sendzyy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACRCiYWdiCswCYB-9CdRIy5U_45rbgxW4',
    appId: '1:316353739480:ios:5edd1b7e307ba47a02b5ad',
    messagingSenderId: '316353739480',
    projectId: 'sendzyy',
    storageBucket: 'sendzyy.firebasestorage.app',
    iosBundleId: 'com.iflorainfopvtltd.sendzyy',
  );
}
